DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS albums;

CREATE TABLE albums (
id SERIAL4 PRIMARY KEY,
title VARCHAR(255),
genre VARCHAR(255)
);

CREATE TABLE artists (
id SERIAL4 PRIMARY KEY,
name VARCHAR(255),
album_id INT4 REFERENCES albums(id)
);